### ISSUE TITLE
Is there a video of this workshop?

### ISSUE THREAD

**Issue by jaredpalmer** [FormidableLabs/dinosaurjs-react-workshop#3]
Would be great to link to this on the Formik docs!

**Comment by chrisbolin** [comment]
@jaredpalmer i'm down!! do you need us to open a PR or can you add it?

**Comment by chrisbolin** [comment]
@jaredpalmer unfortunately we don't have a video of the event :/ But I'll let you know if we do a workshop that is taped. cheers!

**Comment by chrisbolin** [comment]
and if you want to link to this repo without a video, you can definitely do that!
